title: bcf
email: baileycforrest@gmail.com
description: >-
  Bailey Forrest
baseurl: ""
url: "https://bcf.fyi"
twitter_username: baileycforrest
github_username: baileyforrest

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
